### ISSUE TITLE
I get this Reference Code error

### ISSUE THREAD

**Issue by rotimi-best** [ragingwind/now-next-pwa#2]
**Internal Integration Error
Reference Code: GQE8LAWk3GtVPFthviDu
Contact the Integration developer for more information.**

Please what exactly is the error?

**Comment by ragingwind** [comment]
Unfortunately, I have no idea. As I mentioned in readme, it's experimental stage and unexpected behavior would have happened.

**Comment by rotimi-best** [comment]
That's sad, but thanks any way.
